import { MongoMemoryServer } from 'mongodb-memory-server';
import mongoose from 'mongoose';
import express from 'express';
import products from '../routes/products.js';
import warehouses from '../routes/warehouses.js';
import receipts from '../routes/receipts.js';
import ledger from '../routes/ledger.js';

const mongod = await MongoMemoryServer.create();
await mongoose.connect(mongod.getUri());
const app = express();
app.use(express.json());
app.use('/api/products', products);
app.use('/api/warehouses', warehouses);
app.use('/api/receipts', receipts);
app.use('/api/ledger', ledger);
const srv = await new Promise((res) => { const s = app.listen(0, () => res(s)); });
const B = `http://localhost:${srv.address().port}/api`;
const j = (m, p, b) => fetch(`${B}${p}`, { method: m, headers: { 'Content-Type': 'application/json' }, body: b ? JSON.stringify(b) : undefined }).then(async (r) => ({ s: r.status, b: await r.json() }));
const assert = (c, m) => { if (!c) { console.error('FAIL:', m); process.exit(1); } };

const wh = await j('POST', '/warehouses', { name: 'WH', code: 'W1', locations: ['Main Store'] });
assert(wh.s === 201, 'create warehouse ' + wh.s);
const pr = await j('POST', '/products', { name: 'Steel', sku: 'S1', category: 'Raw', uom: 'kg', reorderLevel: 20 });
assert(pr.s === 201, 'create product ' + pr.s);
const rc = await j('POST', '/receipts', { supplier: 'V', warehouse: wh.b._id, lines: [{ product: pr.b._id, qty: 50 }] });
assert(rc.s === 201, 'create receipt ' + rc.s);
const v = await j('POST', `/receipts/${rc.b._id}/validate`, {});
assert(v.b.status === 'Done', 'validate receipt');
const st = await j('GET', `/products/${pr.b._id}/stock`);
assert(st.b[0]?.qty === 50, 'stock +50 via HTTP, got ' + JSON.stringify(st.b));
const lg = await j('GET', '/ledger?type=Receipt');
assert(lg.b.length === 1 && lg.b[0].delta === 50, 'ledger receipt logged');
const dash = await j('GET', '/ledger/dashboard-summary');
assert(dash.b.totalProducts === 1 && dash.b.pendingReceipts === 0, 'dashboard summary ' + JSON.stringify(dash.b));
console.log('HTTP-E2E PASS: warehouse/product/receipt/validate/stock/ledger/dashboard over real HTTP');
srv.close();
await mongoose.disconnect();
await mongod.stop();
